packages:
  - packages/*

overrides:
  swc-plugin-gem: 0.1.18-beta

patchedDependencies:
  '@gem-bind/mermaid@0.0.6': patches/@gem-bind__mermaid@0.0.6.patch
  '@mantou/gem@2.2.13': patches/@mantou__gem@2.2.13.patch
  '@mantou/tap-ui@0.1.13': patches/@mantou__tap-ui@0.1.13.patch
  tailwindcss: patches/tailwindcss.patch
